services:

  mysql:
    image: mysql:8.0.43
    container_name: audio_player_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ports: ${MYSQL_PORT}:3306
    volumes:
      - audio_player_be_mysql_data:/var/lib/mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  audio_player_be_app:
    build: .
    container_name: audio_player_be_app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "${AUDIO_PLAYER_BE_PORT}:8082"
    environment:
      AUDIO_PLAYER_BE_PORT: ${AUDIO_PLAYER_BE_PORT}
      SESSION_TIMEOUT: ${SESSION_TIMEOUT}
      SPRING_APP_NAME: ${SPRING_APP_NAME}

      DB_HOST: mysql
      DB_PORT: 3306                   # Always use MySQL container internal port
      DB_NAME: ${MYSQL_DATABASE}
      DB_PARAMS: useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true

      MYSQL_USERNAME: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

      SPRING_SECURITY_LOGGING_LEVEL: ${SPRING_SECURITY_LOGGING_LEVEL}
      SECURITY_JWT_SECRET: ${SECURITY_JWT_SECRET}

      SCANNING_FOLDERS: /audio-data/songs,/audio-data/top50
      METADATA_REPLACEMENTS_FROM: ${METADATA_REPLACEMENTS_FROM}
      METADATA_REPLACEMENTS_TO: ${METADATA_REPLACEMENTS_TO}

      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    volumes:
      - H:/audio_songs:/audio-data/songs:ro
      - C:/Users/choud/Downloads/Top 50 Single Track:/audio-data/top50:ro

volumes:
  audio_player_be_mysql_data:
    driver: local
