server:
  port: ${AUDIO_PLAYER_BE_PORT:8082}
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:120s}

spring:
  application:
    name: ${SPRING_APP_NAME:Audio player BE}
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:audio_player}?${DB_PARAMS:useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:mysql}
  sql:
    init:
      mode: ${SPRING_SQL_INIT_MODE:ALWAYS}
      data-locations: classpath:/sql/data.sql
#      schema-locations: classpath:/sql/schema.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  output:
    ansi:
      enabled: ALWAYS
      console-available: true
  main:
    allow-bean-definition-overriding: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

logging:
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{15}) - %msg %n"
  level:
    root: INFO
    org:
      apache: INFO
      springframework: INFO
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
    spring:
      security: ${SPRING_SECURITY_LOGGING_LEVEL:TRACE}

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:superSecretKey12345678901234567890}

metadata:
  folders: ${SCANNING_FOLDERS:H:/audio_songs,C:/Users/choud/Downloads/Top 50 Single Track}
  replacements:
    from: ${METADATA_REPLACEMENTS_FROM:(DJJOhAL.Com),(RiskyjaTT.CoM)}
    to: ${METADATA_REPLACEMENTS_TO:}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  exposed-headers:
    - Authorization
    - Content-Length
    - Content-Range
  allow-credentials: true
